package migrations

import (
	"github.com/Caknoooo/go-gin-clean-starter/database"
	"gorm.io/gorm"
)

func init() {
	database.RegisterMigration("20240205153000_remove_cascades", Up20240205153000, Down20240205153000)
}

func Up20240205153000(db *gorm.DB) error {
	// 1. DeviceInstallations -> Devices
	// Drop existing constraint with CASCADE
	db.Exec("ALTER TABLE device_installations DROP CONSTRAINT IF EXISTS fk_device_installations_device")
	// Add new constraint without CASCADE (defaults to NO ACTION/RESTRICT)
	db.Exec("ALTER TABLE device_installations ADD CONSTRAINT fk_device_installations_device FOREIGN KEY (imei) REFERENCES devices(imei)")

	// 2. Positions -> Devices (if it exists)
	// Check if constraint exists or GORM named it differently. Usually fk_positions_device if following conventions or explicit name.
	// In GORM we removed explicit constraint, so we should clean up DB.
	// Since we don't know exact name generated by GORM previously unless we check, let's look for common ones or trust GORM AutoMigrate might have handled it if run, but we want explicit SQL here.
	// Let's inspect known constraints from previous context if possible, or just be safe.
	// Assuming `fk_devices_positions` or similar was not explicitly named in entity but GORM usually generates `fk_<table>_<field>`.
	// For now, let's focus on the one USER complained about explicitly: device_installations_device which we now see as fk_device_installations_device

	// Also RefreshTokens -> User
	db.Exec("ALTER TABLE refresh_tokens DROP CONSTRAINT IF EXISTS fk_refresh_tokens_user")
	db.Exec("ALTER TABLE refresh_tokens ADD CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(id)")

	return nil
}

func Down20240205153000(db *gorm.DB) error {
	return nil
}
