// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.2
// source: proto/device_service.proto

package device_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceService_ListDevicesSimple_FullMethodName = "/target.device.DeviceService/ListDevicesSimple"
	DeviceService_CheckIMEIExists_FullMethodName   = "/target.device.DeviceService/CheckIMEIExists"
	DeviceService_BatchCheckIMEIs_FullMethodName   = "/target.device.DeviceService/BatchCheckIMEIs"
)

// DeviceServiceClient is the client API for DeviceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceServiceClient interface {
	ListDevicesSimple(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	CheckIMEIExists(ctx context.Context, in *CheckIMEIRequest, opts ...grpc.CallOption) (*CheckIMEIResponse, error)
	BatchCheckIMEIs(ctx context.Context, in *BatchCheckIMEIsRequest, opts ...grpc.CallOption) (*BatchCheckIMEIsResponse, error)
}

type deviceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceServiceClient(cc grpc.ClientConnInterface) DeviceServiceClient {
	return &deviceServiceClient{cc}
}

func (c *deviceServiceClient) ListDevicesSimple(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, DeviceService_ListDevicesSimple_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) CheckIMEIExists(ctx context.Context, in *CheckIMEIRequest, opts ...grpc.CallOption) (*CheckIMEIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckIMEIResponse)
	err := c.cc.Invoke(ctx, DeviceService_CheckIMEIExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) BatchCheckIMEIs(ctx context.Context, in *BatchCheckIMEIsRequest, opts ...grpc.CallOption) (*BatchCheckIMEIsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCheckIMEIsResponse)
	err := c.cc.Invoke(ctx, DeviceService_BatchCheckIMEIs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceServiceServer is the server API for DeviceService service.
// All implementations must embed UnimplementedDeviceServiceServer
// for forward compatibility.
type DeviceServiceServer interface {
	ListDevicesSimple(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	CheckIMEIExists(context.Context, *CheckIMEIRequest) (*CheckIMEIResponse, error)
	BatchCheckIMEIs(context.Context, *BatchCheckIMEIsRequest) (*BatchCheckIMEIsResponse, error)
	mustEmbedUnimplementedDeviceServiceServer()
}

// UnimplementedDeviceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceServiceServer struct{}

func (UnimplementedDeviceServiceServer) ListDevicesSimple(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevicesSimple not implemented")
}
func (UnimplementedDeviceServiceServer) CheckIMEIExists(context.Context, *CheckIMEIRequest) (*CheckIMEIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckIMEIExists not implemented")
}
func (UnimplementedDeviceServiceServer) BatchCheckIMEIs(context.Context, *BatchCheckIMEIsRequest) (*BatchCheckIMEIsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCheckIMEIs not implemented")
}
func (UnimplementedDeviceServiceServer) mustEmbedUnimplementedDeviceServiceServer() {}
func (UnimplementedDeviceServiceServer) testEmbeddedByValue()                       {}

// UnsafeDeviceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceServiceServer will
// result in compilation errors.
type UnsafeDeviceServiceServer interface {
	mustEmbedUnimplementedDeviceServiceServer()
}

func RegisterDeviceServiceServer(s grpc.ServiceRegistrar, srv DeviceServiceServer) {
	// If the following call panics, it indicates UnimplementedDeviceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceService_ServiceDesc, srv)
}

func _DeviceService_ListDevicesSimple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).ListDevicesSimple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_ListDevicesSimple_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).ListDevicesSimple(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_CheckIMEIExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckIMEIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).CheckIMEIExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_CheckIMEIExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).CheckIMEIExists(ctx, req.(*CheckIMEIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_BatchCheckIMEIs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCheckIMEIsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).BatchCheckIMEIs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_BatchCheckIMEIs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).BatchCheckIMEIs(ctx, req.(*BatchCheckIMEIsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceService_ServiceDesc is the grpc.ServiceDesc for DeviceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "target.device.DeviceService",
	HandlerType: (*DeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDevicesSimple",
			Handler:    _DeviceService_ListDevicesSimple_Handler,
		},
		{
			MethodName: "CheckIMEIExists",
			Handler:    _DeviceService_CheckIMEIExists_Handler,
		},
		{
			MethodName: "BatchCheckIMEIs",
			Handler:    _DeviceService_BatchCheckIMEIs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/device_service.proto",
}
