// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: proto/device_service.proto

package device_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_proto_device_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_service_proto_rawDescGZIP(), []int{0}
}

type DeviceItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Imei           string                 `protobuf:"bytes,1,opt,name=imei,proto3" json:"imei,omitempty"`
	Model          string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	SimPhoneNumber string                 `protobuf:"bytes,3,opt,name=sim_phone_number,json=simPhoneNumber,proto3" json:"sim_phone_number,omitempty"`
	Status         bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceItem) Reset() {
	*x = DeviceItem{}
	mi := &file_proto_device_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceItem) ProtoMessage() {}

func (x *DeviceItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceItem.ProtoReflect.Descriptor instead.
func (*DeviceItem) Descriptor() ([]byte, []int) {
	return file_proto_device_service_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceItem) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *DeviceItem) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeviceItem) GetSimPhoneNumber() string {
	if x != nil {
		return x.SimPhoneNumber
	}
	return ""
}

func (x *DeviceItem) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceItem          `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_proto_device_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_device_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListDevicesResponse) GetDevices() []*DeviceItem {
	if x != nil {
		return x.Devices
	}
	return nil
}

type CheckIMEIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Imei          string                 `protobuf:"bytes,1,opt,name=imei,proto3" json:"imei,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIMEIRequest) Reset() {
	*x = CheckIMEIRequest{}
	mi := &file_proto_device_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIMEIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIMEIRequest) ProtoMessage() {}

func (x *CheckIMEIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIMEIRequest.ProtoReflect.Descriptor instead.
func (*CheckIMEIRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_service_proto_rawDescGZIP(), []int{3}
}

func (x *CheckIMEIRequest) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

type CheckIMEIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIMEIResponse) Reset() {
	*x = CheckIMEIResponse{}
	mi := &file_proto_device_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIMEIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIMEIResponse) ProtoMessage() {}

func (x *CheckIMEIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIMEIResponse.ProtoReflect.Descriptor instead.
func (*CheckIMEIResponse) Descriptor() ([]byte, []int) {
	return file_proto_device_service_proto_rawDescGZIP(), []int{4}
}

func (x *CheckIMEIResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type BatchCheckIMEIsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Imeis         []string               `protobuf:"bytes,1,rep,name=imeis,proto3" json:"imeis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckIMEIsRequest) Reset() {
	*x = BatchCheckIMEIsRequest{}
	mi := &file_proto_device_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckIMEIsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckIMEIsRequest) ProtoMessage() {}

func (x *BatchCheckIMEIsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckIMEIsRequest.ProtoReflect.Descriptor instead.
func (*BatchCheckIMEIsRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_service_proto_rawDescGZIP(), []int{5}
}

func (x *BatchCheckIMEIsRequest) GetImeis() []string {
	if x != nil {
		return x.Imeis
	}
	return nil
}

type BatchCheckIMEIsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         []string               `protobuf:"bytes,1,rep,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckIMEIsResponse) Reset() {
	*x = BatchCheckIMEIsResponse{}
	mi := &file_proto_device_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckIMEIsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckIMEIsResponse) ProtoMessage() {}

func (x *BatchCheckIMEIsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckIMEIsResponse.ProtoReflect.Descriptor instead.
func (*BatchCheckIMEIsResponse) Descriptor() ([]byte, []int) {
	return file_proto_device_service_proto_rawDescGZIP(), []int{6}
}

func (x *BatchCheckIMEIsResponse) GetFound() []string {
	if x != nil {
		return x.Found
	}
	return nil
}

var File_proto_device_service_proto protoreflect.FileDescriptor

const file_proto_device_service_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/device_service.proto\x12\rtarget.device\"\x14\n" +
	"\x12ListDevicesRequest\"x\n" +
	"\n" +
	"DeviceItem\x12\x12\n" +
	"\x04imei\x18\x01 \x01(\tR\x04imei\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12(\n" +
	"\x10sim_phone_number\x18\x03 \x01(\tR\x0esimPhoneNumber\x12\x16\n" +
	"\x06status\x18\x04 \x01(\bR\x06status\"J\n" +
	"\x13ListDevicesResponse\x123\n" +
	"\adevices\x18\x01 \x03(\v2\x19.target.device.DeviceItemR\adevices\"&\n" +
	"\x10CheckIMEIRequest\x12\x12\n" +
	"\x04imei\x18\x01 \x01(\tR\x04imei\"+\n" +
	"\x11CheckIMEIResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\".\n" +
	"\x16BatchCheckIMEIsRequest\x12\x14\n" +
	"\x05imeis\x18\x01 \x03(\tR\x05imeis\"/\n" +
	"\x17BatchCheckIMEIsResponse\x12\x14\n" +
	"\x05found\x18\x01 \x03(\tR\x05found2\xa3\x02\n" +
	"\rDeviceService\x12Z\n" +
	"\x11ListDevicesSimple\x12!.target.device.ListDevicesRequest\x1a\".target.device.ListDevicesResponse\x12T\n" +
	"\x0fCheckIMEIExists\x12\x1f.target.device.CheckIMEIRequest\x1a .target.device.CheckIMEIResponse\x12`\n" +
	"\x0fBatchCheckIMEIs\x12%.target.device.BatchCheckIMEIsRequest\x1a&.target.device.BatchCheckIMEIsResponseB>Z<github.com/Caknoooo/go-gin-clean-starter/pkg/pb/device_protob\x06proto3"

var (
	file_proto_device_service_proto_rawDescOnce sync.Once
	file_proto_device_service_proto_rawDescData []byte
)

func file_proto_device_service_proto_rawDescGZIP() []byte {
	file_proto_device_service_proto_rawDescOnce.Do(func() {
		file_proto_device_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_device_service_proto_rawDesc), len(file_proto_device_service_proto_rawDesc)))
	})
	return file_proto_device_service_proto_rawDescData
}

var file_proto_device_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_device_service_proto_goTypes = []any{
	(*ListDevicesRequest)(nil),      // 0: target.device.ListDevicesRequest
	(*DeviceItem)(nil),              // 1: target.device.DeviceItem
	(*ListDevicesResponse)(nil),     // 2: target.device.ListDevicesResponse
	(*CheckIMEIRequest)(nil),        // 3: target.device.CheckIMEIRequest
	(*CheckIMEIResponse)(nil),       // 4: target.device.CheckIMEIResponse
	(*BatchCheckIMEIsRequest)(nil),  // 5: target.device.BatchCheckIMEIsRequest
	(*BatchCheckIMEIsResponse)(nil), // 6: target.device.BatchCheckIMEIsResponse
}
var file_proto_device_service_proto_depIdxs = []int32{
	1, // 0: target.device.ListDevicesResponse.devices:type_name -> target.device.DeviceItem
	0, // 1: target.device.DeviceService.ListDevicesSimple:input_type -> target.device.ListDevicesRequest
	3, // 2: target.device.DeviceService.CheckIMEIExists:input_type -> target.device.CheckIMEIRequest
	5, // 3: target.device.DeviceService.BatchCheckIMEIs:input_type -> target.device.BatchCheckIMEIsRequest
	2, // 4: target.device.DeviceService.ListDevicesSimple:output_type -> target.device.ListDevicesResponse
	4, // 5: target.device.DeviceService.CheckIMEIExists:output_type -> target.device.CheckIMEIResponse
	6, // 6: target.device.DeviceService.BatchCheckIMEIs:output_type -> target.device.BatchCheckIMEIsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_device_service_proto_init() }
func file_proto_device_service_proto_init() {
	if File_proto_device_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_device_service_proto_rawDesc), len(file_proto_device_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_device_service_proto_goTypes,
		DependencyIndexes: file_proto_device_service_proto_depIdxs,
		MessageInfos:      file_proto_device_service_proto_msgTypes,
	}.Build()
	File_proto_device_service_proto = out.File
	file_proto_device_service_proto_goTypes = nil
	file_proto_device_service_proto_depIdxs = nil
}
